name: Hello React Breadboard
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x, 20.x, 21.x]
    defaults:
      run:
        working-directory: "samples/Hello React Breadboard"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn build
