# Simple workflow for deploying static content to GitHub Pages
# see https://vitejs.dev/guide/static-deploy#github-pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
      - develop
    paths:
      - samples/DevPulse

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  PAGES_PROJECT_DIR: "samples/DevPulse"
  PAGES_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PAGES_PROJECT_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build --base "${{ env.PAGES_URL }}"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist repository
          path: "./${{ env.PAGES_PROJECT_DIR }}/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
