name: Run all demos
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  WIREIT_FAILURES: "continue"
  WIREIT_LOGGER: "metrics"

jobs:
  Validate_Root:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 19.x
          - 20.x
          - 21.x
        package-manager:
          - yarn
          - npm
    name: Node ${{ matrix.node-version }} ${{ matrix.package-manager }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "${{ matrix.package-manager }}"
      - run: yarn install --frozen-lockfile
        if: matrix.package-manager == 'yarn'
      - run: npm ci
        if: matrix.package-manager == 'npm'
      - run: |
          if [ "${{ matrix.package-manager }}" = "yarn" ]; then
            yarn validate
          else
            npm run validate
          fi
