name: Run all demos
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  WIREIT_FAILURES: "continue"
  WIREIT_LOGGER: "metrics"
  WIREIT_PARALLEL: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        node-version:
          - 19.x
          - 20.x
          - 21.x
        package-manager:
          - yarn
          - npm
        package:
          - ./
          - ./samples/AutoBake
          - ./samples/Breadboard Walkthrough
          - ./samples/CourseCrafter
          - ./samples/Hello World
          - ./samples/TheCritic

    name: ${{ matrix.package }} with Node ${{ matrix.node-version }} ${{ matrix.package-manager }}
    defaults:
      run:
        working-directory: ${{ matrix.package }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "${{ matrix.package-manager }}"
      - name: WireIt Cache
        uses: google/wireit@setup-github-actions-caching/v1

      - run: yarn install
        if: matrix.package-manager == 'yarn'

      - run: yarn validate
        if: matrix.package-manager == 'yarn'
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}

      - run: npm install
        if: matrix.package-manager == 'npm'

      - run: npm run validate
        if: matrix.package-manager == 'npm'

        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
